package com.rules

import com.thizgroup.drools.model.Car;
import com.thizgroup.drools.model.Person;

rule "test-drool7-older than 60"

when
    $Car : Car( person.age > 60)
then
    $Car.setDiscount(80);
    System.out.println("test-drool7-older than 60 "+$Car.getPerson().getAge());
end

rule "test-drool7-other"

when
    $Car : Car( person.age<=60)
then
    $Car.setDiscount(70);
    System.out.println("test-drool7-other "+$Car.getPerson().getAge());
end
